# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python\gradient\ui.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(713, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 370, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 351, 321))
        self.groupBox.setObjectName("groupBox")
        self.groupBox.setVisible(False)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(6, 12, 341, 301))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label.setScaledContents(True)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 0, 351, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_2.setVisible(False)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(6, 12, 341, 311))
        self.label_2.setObjectName("label_2")
        self.label_2.setScaledContents(True)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(260, 330, 451, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_3.setVisible(False)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(60, 20, 111, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(260, 20, 111, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setGeometry(QtCore.QRect(60, 50, 181, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setVisible(False)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(260, 50, 181, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setVisible(False)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 90, 111, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(-1)
        self.comboBox_2.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gradient Image"))
        self.pushButton.setText(_translate("MainWindow", "Load Image"))
        self.groupBox.setTitle(_translate("MainWindow", "Input Image"))
        #self.label.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output Image"))
        #self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Options"))
        self.radioButton.setText(_translate("MainWindow", "OpenCV Colormap"))
        self.radioButton_2.setText(_translate("MainWindow", "Custom Colormap"))
        self.comboBox.setItemText(0, _translate("MainWindow", "JET"))
        self.comboBox.setItemText(1, _translate("MainWindow", "HSV"))
        self.comboBox.setItemText(2, _translate("MainWindow", "COOL"))
        self.comboBox.setItemText(3, _translate("MainWindow", "RAINBOW"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "SingleChannel"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "MultiChannel"))
        self.pushButton_2.setText(_translate("MainWindow", "Gradient"))

